// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (
  id, tracker_id
) VALUES (
  $1, $2
)
RETURNING id, tracker_id, created_at, modified_at
`

type CreateBoardParams struct {
	ID        uuid.UUID `json:"id"`
	TrackerID uuid.UUID `json:"tracker_id"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.ID, arg.TrackerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, tracker_id, created_at, modified_at FROM boards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getBoardByTrackerId = `-- name: GetBoardByTrackerId :one
SELECT id, tracker_id, created_at, modified_at FROM boards
WHERE tracker_id = $1 LIMIT 1
`

func (q *Queries) GetBoardByTrackerId(ctx context.Context, trackerID uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByTrackerId, trackerID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
