// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (
  id, board_id, name, position
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, board_id, name, position, created_at, modified_at
`

type CreateColumnParams struct {
	ID       uuid.UUID `json:"id"`
	BoardID  uuid.UUID `json:"board_id"`
	Name     string    `json:"name"`
	Position int32     `json:"position"`
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn,
		arg.ID,
		arg.BoardID,
		arg.Name,
		arg.Position,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT id, board_id, name, position, created_at, modified_at FROM columns
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetColumn(ctx context.Context, id uuid.UUID) (Column, error) {
	row := q.db.QueryRow(ctx, getColumn, id)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listColumnsByBoard = `-- name: ListColumnsByBoard :many
SELECT id, board_id, name, position, created_at, modified_at FROM columns
WHERE board_id = $1
ORDER BY position ASC
`

func (q *Queries) ListColumnsByBoard(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.Query(ctx, listColumnsByBoard, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Column{}
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumn = `-- name: UpdateColumn :one
UPDATE columns
SET
  name = COALESCE($1, name),
  position = COALESCE($2, position),
  modified_at = COALESCE($3, modified_at)
WHERE
  id = $4
RETURNING id, board_id, name, position, created_at, modified_at
`

type UpdateColumnParams struct {
	Name       pgtype.Text        `json:"name"`
	Position   pgtype.Int4        `json:"position"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, updateColumn,
		arg.Name,
		arg.Position,
		arg.ModifiedAt,
		arg.ID,
	)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
