// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (
  id, column_id, name, status, frequency, time_spent_minutes
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, column_id, name, created_at, modified_at, frequency, status, time_spent_minutes
`

type CreateHabitParams struct {
	ID               uuid.UUID `json:"id"`
	ColumnID         uuid.UUID `json:"column_id"`
	Name             string    `json:"name"`
	Status           bool      `json:"status"`
	Frequency        []int32   `json:"frequency"`
	TimeSpentMinutes int32     `json:"time_spent_minutes"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.ID,
		arg.ColumnID,
		arg.Name,
		arg.Status,
		arg.Frequency,
		arg.TimeSpentMinutes,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Frequency,
		&i.Status,
		&i.TimeSpentMinutes,
	)
	return i, err
}

const getHabit = `-- name: GetHabit :one
SELECT id, column_id, name, created_at, modified_at, frequency, status, time_spent_minutes FROM habits
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHabit(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Frequency,
		&i.Status,
		&i.TimeSpentMinutes,
	)
	return i, err
}

const listHabits = `-- name: ListHabits :many
SELECT id, column_id, name, created_at, modified_at, frequency, status, time_spent_minutes FROM habits
`

func (q *Queries) ListHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Frequency,
			&i.Status,
			&i.TimeSpentMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByColumn = `-- name: ListHabitsByColumn :many
SELECT id, column_id, name, created_at, modified_at, frequency, status, time_spent_minutes FROM habits
WHERE column_id = $1
`

func (q *Queries) ListHabitsByColumn(ctx context.Context, columnID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabitsByColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Frequency,
			&i.Status,
			&i.TimeSpentMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabitsByTracker = `-- name: ListHabitsByTracker :many
SELECT h.id, h.column_id, h.name, h.created_at, h.modified_at, h.frequency, h.status, h.time_spent_minutes
FROM habits h
JOIN columns c ON c.id = h.column_id
JOIN boards b ON b.id = c.board_id
WHERE b.tracker_id = $1
ORDER BY c.position, h.created_at
`

func (q *Queries) ListHabitsByTracker(ctx context.Context, trackerID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabitsByTracker, trackerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Name,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.Frequency,
			&i.Status,
			&i.TimeSpentMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET
  column_id = COALESCE($1, column_id),
  name = COALESCE($2, name),
  status = COALESCE($3, status),
  frequency = COALESCE($4, frequency),
  time_spent_minutes = COALESCE($5, time_spent_minutes),
  modified_at = COALESCE($6, modified_at)
WHERE
  id = $7
RETURNING id, column_id, name, created_at, modified_at, frequency, status, time_spent_minutes
`

type UpdateHabitParams struct {
	ColumnID         pgtype.UUID        `json:"column_id"`
	Name             pgtype.Text        `json:"name"`
	Status           pgtype.Bool        `json:"status"`
	Frequency        []int32            `json:"frequency"`
	TimeSpentMinutes pgtype.Int4        `json:"time_spent_minutes"`
	ModifiedAt       pgtype.Timestamptz `json:"modified_at"`
	ID               uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.ColumnID,
		arg.Name,
		arg.Status,
		arg.Frequency,
		arg.TimeSpentMinutes,
		arg.ModifiedAt,
		arg.ID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Name,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.Frequency,
		&i.Status,
		&i.TimeSpentMinutes,
	)
	return i, err
}
