// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (
  id, tracker_id, name, description, status, modified_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, tracker_id, name, description, status, modified_at, created_at
`

type CreateHabitParams struct {
	ID          uuid.UUID `json:"id"`
	TrackerID   uuid.UUID `json:"tracker_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	ModifiedAt  time.Time `json:"modified_at"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.ID,
		arg.TrackerID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ModifiedAt,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ModifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHabit = `-- name: GetHabit :one
SELECT id, tracker_id, name, description, status, modified_at, created_at FROM habits
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHabit(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ModifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listHabits = `-- name: ListHabits :many
SELECT id, tracker_id, name, description, status, modified_at, created_at FROM habits
`

func (q *Queries) ListHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.TrackerID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.ModifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET
  tracker_id = COALESCE($1, tracker_id),
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  status = COALESCE($4, status),
  modified_at = COALESCE($5, modified_at)
WHERE
  id = $6
RETURNING id, tracker_id, name, description, status, modified_at, created_at
`

type UpdateHabitParams struct {
	TrackerID   pgtype.UUID        `json:"tracker_id"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	Status      pgtype.Text        `json:"status"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.TrackerID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ModifiedAt,
		arg.ID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.TrackerID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ModifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
