// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits_entry.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHabitEntry = `-- name: CreateHabitEntry :one
INSERT INTO habit_entry (
  id, habit_id, date, completed
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, habit_id, date, completed, created_at, modified_at
`

type CreateHabitEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	HabitID   uuid.UUID   `json:"habit_id"`
	Date      pgtype.Date `json:"date"`
	Completed bool        `json:"completed"`
}

func (q *Queries) CreateHabitEntry(ctx context.Context, arg CreateHabitEntryParams) (HabitEntry, error) {
	row := q.db.QueryRow(ctx, createHabitEntry,
		arg.ID,
		arg.HabitID,
		arg.Date,
		arg.Completed,
	)
	var i HabitEntry
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getHabitEntry = `-- name: GetHabitEntry :one
SELECT id, habit_id, date, completed, created_at, modified_at FROM habit_entry
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHabitEntry(ctx context.Context, id uuid.UUID) (HabitEntry, error) {
	row := q.db.QueryRow(ctx, getHabitEntry, id)
	var i HabitEntry
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const listHabitEntries = `-- name: ListHabitEntries :many
SELECT id, habit_id, date, completed, created_at, modified_at FROM habit_entry
`

func (q *Queries) ListHabitEntries(ctx context.Context) ([]HabitEntry, error) {
	rows, err := q.db.Query(ctx, listHabitEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitEntry{}
	for rows.Next() {
		var i HabitEntry
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.Date,
			&i.Completed,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabitEntry = `-- name: UpdateHabitEntry :one
UPDATE habit_entry
SET
  habit_id = COALESCE($1, habit_id),
  date = COALESCE($2, date),
  completed = COALESCE($3, completed),
  modified_at = COALESCE($4, modified_at)
WHERE
  id = $5
RETURNING id, habit_id, date, completed, created_at, modified_at
`

type UpdateHabitEntryParams struct {
	HabitID    pgtype.UUID        `json:"habit_id"`
	Date       pgtype.Date        `json:"date"`
	Completed  pgtype.Bool        `json:"completed"`
	ModifiedAt pgtype.Timestamptz `json:"modified_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateHabitEntry(ctx context.Context, arg UpdateHabitEntryParams) (HabitEntry, error) {
	row := q.db.QueryRow(ctx, updateHabitEntry,
		arg.HabitID,
		arg.Date,
		arg.Completed,
		arg.ModifiedAt,
		arg.ID,
	)
	var i HabitEntry
	err := row.Scan(
		&i.ID,
		&i.HabitID,
		&i.Date,
		&i.Completed,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
