// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error)
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateHabitEntry(ctx context.Context, arg CreateHabitEntryParams) (HabitEntry, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTracker(ctx context.Context, arg CreateTrackerParams) (Tracker, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBoard(ctx context.Context, id uuid.UUID) (Board, error)
	GetBoardByTrackerId(ctx context.Context, trackerID uuid.UUID) (Board, error)
	GetColumn(ctx context.Context, id uuid.UUID) (Column, error)
	GetHabit(ctx context.Context, id uuid.UUID) (Habit, error)
	GetHabitEntry(ctx context.Context, id uuid.UUID) (HabitEntry, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTracker(ctx context.Context, id uuid.UUID) (Tracker, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListColumns(ctx context.Context) ([]Column, error)
	ListHabitEntries(ctx context.Context) ([]HabitEntry, error)
	ListHabits(ctx context.Context) ([]Habit, error)
	ListTrackers(ctx context.Context) ([]Tracker, error)
	UpdateColumn(ctx context.Context, arg UpdateColumnParams) (Column, error)
	UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error)
	UpdateHabitEntry(ctx context.Context, arg UpdateHabitEntryParams) (HabitEntry, error)
	UpdateTracker(ctx context.Context, arg UpdateTrackerParams) (Tracker, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
