// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trackers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTracker = `-- name: CreateTracker :one
INSERT INTO trackers (
  id, username, name, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, username, name, modified_at, created_at, description
`

type CreateTrackerParams struct {
	ID          uuid.UUID `json:"id"`
	Username    string    `json:"username"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) CreateTracker(ctx context.Context, arg CreateTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, createTracker,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Description,
	)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.ModifiedAt,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const getTracker = `-- name: GetTracker :one
SELECT id, username, name, modified_at, created_at, description FROM trackers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTracker(ctx context.Context, id uuid.UUID) (Tracker, error) {
	row := q.db.QueryRow(ctx, getTracker, id)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.ModifiedAt,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}

const listTrackers = `-- name: ListTrackers :many
SELECT id, username, name, modified_at, created_at, description FROM trackers
`

func (q *Queries) ListTrackers(ctx context.Context) ([]Tracker, error) {
	rows, err := q.db.Query(ctx, listTrackers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tracker{}
	for rows.Next() {
		var i Tracker
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.ModifiedAt,
			&i.CreatedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTracker = `-- name: UpdateTracker :one
UPDATE trackers
SET
  username = COALESCE($1, username),
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  modified_at = COALESCE($4, modified_at)
WHERE
  id = $5
RETURNING id, username, name, modified_at, created_at, description
`

type UpdateTrackerParams struct {
	Username    pgtype.Text        `json:"username"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	ModifiedAt  pgtype.Timestamptz `json:"modified_at"`
	ID          uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateTracker(ctx context.Context, arg UpdateTrackerParams) (Tracker, error) {
	row := q.db.QueryRow(ctx, updateTracker,
		arg.Username,
		arg.Name,
		arg.Description,
		arg.ModifiedAt,
		arg.ID,
	)
	var i Tracker
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.ModifiedAt,
		&i.CreatedAt,
		&i.Description,
	)
	return i, err
}
